import type { BlueprintGroup } from "./types";

const LOGO = (slug: string, color?: string) =>
  `https://cdn.simpleicons.org/${slug}${color ? `/${color}` : ""}`;

export const databasesGroup: BlueprintGroup = {
  id: "databases",
  name: "Databases",
  description: "Reusable database stacks with backup and monitoring.",
  logo: LOGO("postgresql", "4169E1"),
  blueprints: [
    {
      id: "postgres-ha",
      name: "PostgreSQL HA (Patroni + etcd)",
      description:
        "3-node PostgreSQL HA cluster managed by Patroni with an embedded etcd v3 DCS. Installs PostgreSQL from PGDG, runs Patroni from a pinned Python venv, and manages everything via systemd. First node is the initial leader; use 3+ nodes for real HA.",
      logo: LOGO("postgresql", "4169E1"),
      tags: ["postgres", "patroni", "etcd", "ha", "systemd"],
      author: "opensible",
      stars: 112,
      available: true,
      path: "IaC/blueprints/databases/postgres-patroni",
      templateId: "postgres-patroni",
      filenameStem: "postgres-patroni-cluster",
      defaults: {
        cluster_id: "opensible-pg",
        pg_version: "16",
        ssh_user_default: "root",
        ssh_port_default: 22,
        nodes: [
          { name: "pg-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "pg-2", ip: "", ssh_user: "", ssh_port: "" },
          { name: "pg-3", ip: "", ssh_user: "", ssh_port: "" },
        ],
        listen_address: "0.0.0.0",
        pg_port: 5432,
        patroni_rest_port: 8008,
        etcd_client_port: 2379,
        etcd_peer_port: 2380,
        synchronous_mode: false,
        maximum_lag_on_failover: 1048576,
        ttl: 30,
        loop_wait: 10,
        retry_timeout: 10,
        max_connections: 200,
        shared_buffers: "256MB",
        wal_level: "replica",
        etcd_version: "3.5.16",
        patroni_version: "3.3.2",
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "mongodb-rs",
      name: "MongoDB Replica Set",
      description: "3-node MongoDB replica set with TLS and rolling backups.",
      logo: LOGO("mongodb", "47A248"),
      tags: ["mongodb", "replica"],
      stars: 58,
    },
    {
      id: "redis-sentinel",
      name: "Redis + Sentinel",
      description:
        "Redis primary/replica with Sentinel for automatic failover. Distro packages + systemd — no Docker, no Bitnami. First node is the initial primary; add 3+ nodes for real HA.",
      logo: LOGO("redis", "DC382D"),
      tags: ["redis", "sentinel", "ha", "systemd"],
      author: "opensible",
      stars: 47,
      available: true,
      path: "IaC/blueprints/databases/redis-sentinel",
      templateId: "redis-sentinel",
      filenameStem: "redis-sentinel-cluster",
      defaults: {
        flavor: "redis",
        cluster_id: "opensible-redis",
        primary_name: "mymaster",
        bind: "0.0.0.0",
        port: 6379,
        sentinel_port: 26379,
        quorum: 2,
        down_after_ms: 5000,
        failover_timeout_ms: 10000,
        parallel_syncs: 1,
        maxmemory: "",
        maxmemory_policy: "noeviction",
        appendonly: true,
        requirepass: "",
        ssh_user_default: "root",
        ssh_port_default: 22,
        nodes: [
          { name: "redis-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "redis-2", ip: "", ssh_user: "", ssh_port: "" },
          { name: "redis-3", ip: "", ssh_user: "", ssh_port: "" },
        ],
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "valkey-sentinel",
      name: "Valkey + Sentinel",
      description:
        "Valkey (open-source Redis fork) primary/replica with Sentinel for automatic failover. Distro packages + systemd — no Docker, no Bitnami. First node is the initial primary; add 3+ nodes for real HA.",
      logo: "https://raw.githubusercontent.com/valkey-io/valkey/unstable/BRANDING/valkey-logomark.svg",
      tags: ["valkey", "sentinel", "ha", "systemd"],
      author: "opensible",
      stars: 21,
      available: true,
      path: "IaC/blueprints/databases/valkey-sentinel",
      templateId: "redis-sentinel",
      filenameStem: "valkey-sentinel-cluster",
      defaults: {
        flavor: "valkey",
        cluster_id: "opensible-valkey",
        primary_name: "mymaster",
        bind: "0.0.0.0",
        port: 6379,
        sentinel_port: 26379,
        quorum: 2,
        down_after_ms: 5000,
        failover_timeout_ms: 10000,
        parallel_syncs: 1,
        maxmemory: "",
        maxmemory_policy: "noeviction",
        appendonly: true,
        requirepass: "",
        ssh_user_default: "root",
        ssh_port_default: 22,
        nodes: [
          { name: "valkey-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "valkey-2", ip: "", ssh_user: "", ssh_port: "" },
          { name: "valkey-3", ip: "", ssh_user: "", ssh_port: "" },
        ],
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "elasticsearch-cluster",
      name: "Elasticsearch HA (Docker cluster)",
      description:
        "Production Elasticsearch cluster across N nodes running the official Elasticsearch Docker image. Each node runs one container managed by a dedicated systemd unit; cluster formation via discovery.seed_hosts and cluster.initial_master_nodes. Ships with a per-node HTTP health dashboard (green/yellow/red + shard summary).",
      logo: LOGO("elasticsearch", "005571"),
      tags: ["elasticsearch", "elastic", "docker", "cluster", "ha", "search"],
      author: "opensible",
      stars: 34,
      available: true,
      path: "IaC/blueprints/databases/elasticsearch-cluster",
      templateId: "elasticsearch-cluster",
      filenameStem: "elasticsearch-cluster",
      defaults: {
        cluster_id: "opensible-es",
        es_version: "8.15.3",
        http_port: 9200,
        transport_port: 9300,
        announce_host: "{{ ansible_host | default(inventory_hostname) }}",
        health_http_enabled: true,
        health_http_port: 9280,
        security_enabled: false,
        elastic_password: "",
        heap_size: "1g",
        data_dir: "/var/lib/elasticsearch-data",
        ssh_user_default: "root",
        ssh_port_default: 22,
        nodes: [
          { name: "es-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "es-2", ip: "", ssh_user: "", ssh_port: "" },
          { name: "es-3", ip: "", ssh_user: "", ssh_port: "" },
        ],
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "kibana-cluster",
      name: "Kibana HA (Docker cluster)",
      description:
        "Multi-node Kibana deployment (recommended 2 or 3 behind a load balancer) running the official Kibana Docker image. Every node runs one container managed by a dedicated systemd unit, all pointing at the same Elasticsearch backend via ELASTICSEARCH_HOSTS. Ships with a per-node HTTP health dashboard exposing Kibana + upstream Elasticsearch status.",
      logo: LOGO("kibana", "005571"),
      tags: ["kibana", "elastic", "docker", "cluster", "ha", "observability"],
      author: "opensible",
      stars: 21,
      available: true,
      path: "IaC/blueprints/databases/kibana-cluster",
      templateId: "kibana-cluster",
      filenameStem: "kibana-cluster",
      defaults: {
        cluster_id: "opensible-kibana",
        kibana_version: "8.15.3",
        http_port: 5601,
        server_publicBaseUrl: "",
        health_http_enabled: true,
        health_http_port: 5680,
        elasticsearch_hosts:
          "http://10.0.0.11:9200,http://10.0.0.12:9200,http://10.0.0.13:9200",
        security_enabled: false,
        elasticsearch_username: "kibana_system",
        elasticsearch_password: "",
        elasticsearch_ssl_verificationMode: "full",
        elasticsearch_requestTimeout: 300000,
        elasticsearch_pingTimeout: 60000,
        elasticsearch_shardTimeout: 120000,
        elasticsearch_sniffOnStart: false,
        kibana_lightweight_mode: true,
        task_manager_maxWorkers: 5,
        task_manager_pollInterval: 10000,
        encryption_key: "",
        ssh_user_default: "root",
        ssh_port_default: 22,
        nodes: [
          { name: "kibana-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "kibana-2", ip: "", ssh_user: "", ssh_port: "" },
        ],
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "logstash-cluster",
      name: "Logstash HA (Docker cluster)",
      description:
        "Multi-node Logstash deployment running the official Logstash Docker image. Every node runs one container managed by a dedicated systemd unit, sharing the same pipeline configuration and writing to the same Elasticsearch backend. Ships with a default beats-in / elasticsearch-out pipeline and a per-node HTTP health dashboard exposing Logstash node + pipeline stats and upstream Elasticsearch reachability.",
      logo: LOGO("logstash", "005571"),
      tags: ["logstash", "elastic", "docker", "cluster", "ha", "pipeline", "ingest"],
      author: "opensible",
      stars: 18,
      available: true,
      path: "IaC/blueprints/databases/logstash-cluster",
      templateId: "logstash-cluster",
      filenameStem: "logstash-cluster",
      defaults: {
        cluster_id: "opensible-logstash",
        logstash_version: "8.15.3",
        beats_port: 5044,
        http_api_port: 9600,
        health_http_enabled: true,
        health_http_port: 9680,
        elasticsearch_hosts:
          "http://10.0.0.11:9200,http://10.0.0.12:9200,http://10.0.0.13:9200",
        security_enabled: false,
        elasticsearch_username: "elastic",
        elasticsearch_password: "",
        elasticsearch_ssl_verificationMode: "full",
        pipeline_workers: 2,
        pipeline_batch_size: 125,
        heap_size: "1g",
        index_pattern: "logs-%{+YYYY.MM.dd}",
        ssh_user_default: "root",
        ssh_port_default: 22,
        nodes: [
          { name: "logstash-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "logstash-2", ip: "", ssh_user: "", ssh_port: "" },
        ],
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "mysql-group",
      name: "MySQL Group Replication",
      description: "MySQL 8 group replication with ProxySQL routing.",
      logo: LOGO("mysql", "4479A1"),
      tags: ["mysql"],
      stars: 33,
    },
  ],
};
