import type { BlueprintGroup } from "./types";

const LOGO = (slug: string, color?: string) =>
  `https://cdn.simpleicons.org/${slug}${color ? `/${color}` : ""}`;

export const dockerGroup: BlueprintGroup = {
  id: "docker",
  name: "Docker & Containers",
  description: "Blueprints for container engines and compose-based stacks.",
  logo: LOGO("docker", "2496ED"),
  blueprints: [
    {
      id: "docker-engine",
      name: "Docker Engine",
      description: "Install and harden Docker Engine with buildx and compose plugin.",
      logo: LOGO("docker", "2496ED"),
      tags: ["docker", "engine"],
      author: "opensible",
      stars: 82,
      available: true,
      path: "IaC/blueprints/docker/docker-engine",
      templateId: "docker-engine",
      filenameStem: "docker-engine",
    },
    {
      id: "portainer-ce",
      name: "Portainer CE",
      description: "Deploy Portainer CE for container management across nodes.",
      logo: LOGO("portainer", "13BEF9"),
      tags: ["portainer", "ui"],
      stars: 41,
    },
    {
      id: "traefik-proxy-docker",
      name: "Traefik Reverse Proxy (Docker provider)",
      description:
        "Traefik v3 on systemd with the Docker provider enabled — auto-discovers containers on the host's Docker socket via `traefik.enable=true` labels, exposes the protected dashboard, Prometheus metrics and optional Let's Encrypt ACME. Deploy as a single node or as an HA cluster with a keepalived VRRP virtual IP.",
      logo: LOGO("traefikproxy", "24A1C1"),
      tags: ["traefik", "reverse-proxy", "docker", "tls", "systemd"],
      author: "opensible",
      stars: 63,
      available: true,
      path: "IaC/blueprints/networking/traefik",
      templateId: "traefik-proxy",
      filenameStem: "traefik-proxy-docker",
      defaults: {
        cluster_id: "opensible-traefik-docker",
        deploy_mode: "single",
        traefik_version: "3.2.1",
        http_port: 80,
        https_enabled: true,
        https_port: 443,
        http_to_https_redirect: true,
        dashboard_enabled: true,
        dashboard_port: 8080,
        dashboard_user: "admin",
        dashboard_password: "",
        docker_provider: true,
        docker_expose_by_default: false,
        file_provider_dir: "/etc/traefik/dynamic",
        acme_enabled: false,
        acme_email: "",
        acme_staging: false,
        access_log_enabled: true,
        metrics_enabled: true,
        keepalived_enabled: false,
        vrrp_vip: "",
        vrrp_interface: "eth0",
        vrrp_router_id: 52,
        vrrp_password: "",
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "docker-compose",
      name: "Docker Compose Stack",
      description:
        "Render a docker-compose.yml on target hosts and run `docker compose up -d`. Ships with the compose plugin, per-host env files and idempotent restart handling.",
      logo: LOGO("docker", "2496ED"),
      tags: ["docker", "compose"],
      author: "opensible",
      stars: 54,
      available: true,
      templateId: "docker-compose",
      filenameStem: "docker-compose",
    },
    {
      id: "nginx-reverse-proxy",
      name: "NGINX Reverse Proxy",
      description:
        "Install NGINX from distro packages and render a hardened reverse-proxy vhost with optional TLS, HTTP→HTTPS redirect and upstream health checks.",
      logo: LOGO("nginx", "009639"),
      tags: ["nginx", "reverse-proxy", "tls"],
      author: "opensible",
      stars: 47,
      available: true,
      templateId: "nginx-reverse-proxy",
      filenameStem: "nginx-reverse-proxy",
    },
  ],
};
