import type { BlueprintGroup } from "./types";

const LOGO = (slug: string, color?: string) =>
  `https://cdn.simpleicons.org/${slug}${color ? `/${color}` : ""}`;

export const observabilityGroup: BlueprintGroup = {
  id: "observability",
  name: "Observability",
  description: "Metrics, logs and tracing stacks.",
  logo: LOGO("prometheus", "E6522C"),
  blueprints: [
    {
      id: "grafana-oss",
      name: "Grafana OSS",
      description:
        "Grafana OSS from the official apt/dnf repository on systemd. Admin creds and listen port injected via a systemd drop-in; can pre-provision a Prometheus / VictoriaMetrics datasource so dashboards work on first boot.",
      logo: LOGO("grafana", "F46800"),
      tags: ["grafana", "dashboards", "systemd"],
      author: "opensible",
      stars: 41,
      available: true,
      path: "IaC/blueprints/observability/grafana",
      templateId: "grafana-oss",
      filenameStem: "grafana-oss",
      defaults: {
        cluster_id: "opensible-grafana",
        grafana_version: "11.3.0",
        listen_port: 3000,
        admin_user: "admin",
        admin_password: "",
        anonymous_enabled: false,
        root_url: "",
        datasource_url: "",
        datasource_name: "Prometheus",
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "metrics-server",
      name: "Prometheus / VictoriaMetrics",
      description:
        "Single-node metrics backend on systemd (no Docker). Choose Prometheus (with a rendered scrape config for your node_exporter targets) or VictoriaMetrics (drop-in Prometheus API, lower RAM and better compression).",
      logo: LOGO("victoriametrics", "621773"),
      tags: ["prometheus", "victoriametrics", "metrics", "systemd"],
      author: "opensible",
      stars: 37,
      available: true,
      path: "IaC/blueprints/observability/metrics-server",
      templateId: "metrics-server",
      filenameStem: "metrics-server",
      defaults: {
        cluster_id: "opensible-metrics",
        backend: "victoriametrics",
        vm_version: "1.145.0",
        prometheus_version: "2.55.1",
        listen_port: 8428,
        retention: "90d",
        data_dir: "/srv/metrics",
        scrape_interval: "15s",
        node_exporter_targets: "# - 10.0.0.10:9100\n# - 10.0.0.11:9100\n",
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "node-exporter",
      name: "Prometheus node_exporter",
      description:
        "Install prometheus-node-exporter on every selected host from distro packages (Debian/Ubuntu + RHEL/Rocky/Alma via EPEL). Exposes host metrics on :9100/metrics with the textfile collector enabled.",
      logo: LOGO("prometheus", "E6522C"),
      tags: ["prometheus", "node-exporter", "metrics", "systemd"],
      author: "opensible",
      stars: 29,
      available: true,
      path: "IaC/blueprints/observability/node-exporter",
      templateId: "node-exporter",
      filenameStem: "node-exporter",
      defaults: {
        cluster_id: "opensible-node-exporter",
        listen_address: "0.0.0.0:9100",
        textfile_dir: "/var/lib/node_exporter/textfile_collector",
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "kube-prometheus",
      name: "kube-prometheus-stack",
      description: "Prometheus, Alertmanager and Grafana via Helm with default dashboards.",
      logo: LOGO("prometheus", "E6522C"),
      tags: ["prometheus", "grafana"],
      stars: 145,
    },
    {
      id: "loki-stack",
      name: "Loki + Promtail",
      description: "Log aggregation with Loki and Promtail agents, wired to Grafana.",
      logo: LOGO("grafana", "F46800"),
      tags: ["loki", "logs"],
      stars: 61,
    },
    {
      id: "opentelemetry",
      name: "OpenTelemetry Collector",
      description: "OTel collector DaemonSet with OTLP receivers and multi-exporter pipeline.",
      logo: LOGO("opentelemetry", "000000"),
      tags: ["otel", "tracing"],
      stars: 39,
    },
  ],
};


export const securityGroup: BlueprintGroup = {
  id: "security",
  name: "Security & Secrets",
  description: "Secret management and hardening blueprints.",
  logo: LOGO("vault", "FFEC6E"),
  blueprints: [
    {
      id: "openbao",
      name: "OpenBao Cluster (Raft HA)",
      description:
        "HashiCorp Vault–compatible OpenBao on systemd (no Docker). Installs from pinned official release assets without GitHub API calls, renders /etc/openbao/openbao.hcl with integrated Raft storage, cross-node retry_join for HA, and can auto-init + unseal every node on the first run.",
      logo: LOGO("vault", "FFEC6E"),
      tags: ["secrets", "openbao", "vault", "raft", "systemd"],
      author: "opensible",
      stars: 44,
      available: true,
      path: "IaC/blueprints/security/openbao",
      templateId: "openbao-systemd",
      filenameStem: "openbao-cluster",
      defaults: {
        cluster_id: "opensible-bao",
        ssh_user_default: "root",
        ssh_port_default: 22,
        nodes: [
          { name: "bao-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "bao-2", ip: "", ssh_user: "", ssh_port: "" },
          { name: "bao-3", ip: "", ssh_user: "", ssh_port: "" },
        ],
        version: "2.6.0",
        listen_address: "0.0.0.0:8200",
        cluster_address: "",
        api_address: "",
        tls_disable: true,
        tls_cert_file: "/etc/openbao/tls/tls.crt",
        tls_key_file: "/etc/openbao/tls/tls.key",
        storage_backend: "raft",
        raft_node_id: "{{ inventory_hostname }}",
        data_dir: "/opt/openbao/data",
        ui: true,
        disable_mlock: true,
        log_level: "info",
        auto_init: true,
        health_http_enabled: true,
        health_http_port: 8280,
        become: true,

      },
    },
    {
      id: "vault-cluster",
      name: "HashiCorp Vault HA (Docker cluster)",
      description:
        "Production HashiCorp Vault HA cluster across N nodes running the official hashicorp/vault Docker image with integrated Raft storage. Each node runs one container managed by a dedicated systemd unit (vault-docker.service); followers auto-join via retry_join, and optional first-run auto-init + persistent auto-unseal keep the cluster unsealed across reboots.",
      logo: LOGO("vault", "FFEC6E"),
      tags: ["vault", "hashicorp", "secrets", "docker", "cluster", "ha", "raft"],
      author: "opensible",
      stars: 12,
      available: true,
      path: "IaC/blueprints/security/vault-cluster",
      templateId: "vault-cluster",
      filenameStem: "vault-cluster",
      defaults: {
        cluster_id: "opensible-vault",
        ssh_user_default: "root",
        ssh_port_default: 22,
        nodes: [
          { name: "vault-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "vault-2", ip: "", ssh_user: "", ssh_port: "" },
          { name: "vault-3", ip: "", ssh_user: "", ssh_port: "" },
        ],
        vault_version: "1.18.1",
        api_port: 8200,
        cluster_port: 8201,
        api_address: "",
        cluster_address: "",
        tls_disable: true,
        tls_cert_file: "/etc/vault/tls/tls.crt",
        tls_key_file: "/etc/vault/tls/tls.key",
        data_dir: "/var/lib/vault-data",
        ui: true,
        disable_mlock: true,
        log_level: "info",
        auto_init: true,
        health_http_enabled: true,
        health_http_port: 8280,
        open_firewall: true,
        become: true,

      },
    },
    {
      id: "cert-manager",
      name: "cert-manager + Cloudflare",
      description: "Automated TLS with cert-manager and Cloudflare DNS-01 solver.",
      logo: LOGO("letsencrypt", "003A70"),
      tags: ["tls", "cert-manager"],
      stars: 52,
    },
    {
      id: "cis-hardening",
      name: "Linux CIS Hardening",
      description: "Apply CIS Level 1 benchmark to Ubuntu / RHEL hosts.",
      logo: LOGO("linux", "FCC624"),
      tags: ["cis", "hardening"],
      stars: 28,
    },
    {
      id: "haproxy-lb",
      name: "HAProxy Load Balancer",
      description:
        "HAProxy L4/L7 load balancer on systemd (distro package). Renders a hardened haproxy.cfg with health checks, a protected stats page and optional TLS termination. Enable keepalived to publish a VRRP virtual IP across 2+ nodes for HA.",
      logo: LOGO("haproxy", "106DA9"),
      tags: ["haproxy", "load-balancer", "keepalived", "ha", "systemd"],
      author: "opensible",
      stars: 22,
      available: true,
      path: "IaC/blueprints/security/haproxy",
      templateId: "haproxy-lb",
      filenameStem: "haproxy-lb",
      defaults: {
        cluster_id: "opensible-haproxy",
        mode: "http",
        frontend_bind: "0.0.0.0",
        frontend_port: 80,
        balance_algorithm: "roundrobin",
        backends: [
          { name: "app-1", ip: "", ssh_user: "", ssh_port: 8080 },
          { name: "app-2", ip: "", ssh_user: "", ssh_port: 8080 },
        ],
        backend_check: true,
        http_check_path: "/",
        tls_enabled: false,
        tls_bind_port: 443,
        tls_cert_path: "/etc/haproxy/certs/site.pem",
        tls_redirect_http: true,
        stats_enabled: true,
        stats_port: 8404,
        stats_uri: "/stats",
        stats_user: "admin",
        stats_password: "",
        maxconn: 20000,
        timeout_client: "30s",
        timeout_server: "30s",
        timeout_connect: "5s",
        extra_global: "",
        extra_defaults: "",
        keepalived_enabled: false,
        vrrp_vip: "",
        vrrp_interface: "eth0",
        vrrp_router_id: 51,
        vrrp_password: "",
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "traefik-proxy",
      name: "Traefik Reverse Proxy / LB",
      description:
        "Traefik v3 reverse proxy on systemd (official GitHub tarball). Hardened static config, file-provider directory for dynamic routes, protected dashboard, Prometheus metrics and optional Let's Encrypt ACME. Deploy as a single instance or as an HA cluster with a keepalived VRRP virtual IP.",
      logo: LOGO("traefikproxy", "24A1C1"),
      tags: ["traefik", "reverse-proxy", "load-balancer", "systemd", "ha"],
      author: "opensible",
      stars: 19,
      available: true,
      path: "IaC/blueprints/networking/traefik",
      templateId: "traefik-proxy",
      filenameStem: "traefik-proxy",
      defaults: {
        cluster_id: "opensible-traefik",
        deploy_mode: "single",
        traefik_version: "3.2.1",
        http_port: 80,
        https_enabled: true,
        https_port: 443,
        http_to_https_redirect: true,
        dashboard_enabled: true,
        dashboard_port: 8080,
        dashboard_user: "admin",
        dashboard_password: "",
        docker_provider: false,
        docker_expose_by_default: false,
        file_provider_dir: "/etc/traefik/dynamic",
        acme_enabled: false,
        acme_email: "",
        acme_staging: false,
        access_log_enabled: true,
        metrics_enabled: true,
        keepalived_enabled: false,
        vrrp_vip: "",
        vrrp_interface: "eth0",
        vrrp_router_id: 52,
        vrrp_password: "",
        open_firewall: true,
        become: true,
      },
    },
  ],
};

export const messagingGroup: BlueprintGroup = {
  id: "messaging",
  name: "Messaging & Streaming",
  description: "Event streaming and message broker stacks.",
  logo: LOGO("apachekafka", "231F20"),
  blueprints: [
    {
      id: "kafka-kraft",
      name: "Apache Kafka (KRaft Cluster)",
      description:
        "Apache Kafka in KRaft mode on systemd (no ZooKeeper, no Docker, no Bitnami). Node IDs, quorum voters and advertised listeners are computed from the inventory.",
      logo: LOGO("apachekafka", "231F20"),
      tags: ["kafka", "kraft", "systemd", "streaming"],
      author: "opensible",
      stars: 76,
      available: true,
      path: "IaC/blueprints/messaging/kafka-kraft",
      templateId: "kafka-cluster",
      filenameStem: "kafka-kraft-cluster",
      defaults: {
        cluster_id: "opensible-kafka",
        kafka_version: "3.8.1",
        kafka_scala_version: "2.13",
        client_port: 9092,
        controller_port: 9093,
        replication_factor: 3,
        min_insync_replicas: 2,
        num_partitions: 6,
        auto_create_topics: false,
        log_retention_hours: 168,
        heap_opts: "-Xms1G -Xmx1G",
        install_dir: "/opt/kafka",
        data_dir: "/var/lib/kafka/data",
        log_dir: "/var/log/kafka",
        ssh_user_default: "root",
        ssh_port_default: 22,
        brokers: [
          { name: "kafka-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "kafka-2", ip: "", ssh_user: "", ssh_port: "" },
          { name: "kafka-3", ip: "", ssh_user: "", ssh_port: "" },
        ],
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "redpanda-cluster",
      name: "Redpanda Cluster (Self-Managed) + Console",
      description:
        "Kafka-API-compatible Redpanda Self-Managed cluster on systemd (no ZooKeeper, no JVM, no Docker). Seed servers and advertised listeners are computed from the inventory. Redpanda Console (web UI) is deployed on the first broker.",
      logo: LOGO("redpanda", "E9165A"),
      tags: ["redpanda", "kafka-api", "systemd", "streaming", "console"],
      author: "opensible",
      stars: 32,
      available: true,
      path: "IaC/blueprints/messaging/redpanda",
      templateId: "redpanda-cluster",
      filenameStem: "redpanda-cluster",
      defaults: {
        cluster_id: "opensible-redpanda",
        redpanda_channel: "redpanda",
        kafka_port: 9092,
        rpc_port: 33145,
        admin_port: 9644,
        schema_registry_port: 8081,
        pandaproxy_port: 8082,
        console_enabled: true,
        console_port: 8080,
        developer_mode: false,
        seastar_smp: 0,
        seastar_memory: "0",
        data_dir: "/var/lib/redpanda/data",
        ssh_user_default: "root",
        ssh_port_default: 22,
        brokers: [
          { name: "redpanda-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "redpanda-2", ip: "", ssh_user: "", ssh_port: "" },
          { name: "redpanda-3", ip: "", ssh_user: "", ssh_port: "" },
        ],
        open_firewall: true,
        become: true,
      },
    },
    {
      id: "rabbitmq-cluster",
      name: "RabbitMQ Cluster",
      description:
        "RabbitMQ cluster with management UI, Prometheus metrics and quorum-queue defaults. Installs from distro packages and manages rabbitmq-server via systemd. First node is the seed; the rest join it. Use 3+ nodes for HA quorum queues.",
      logo: LOGO("rabbitmq", "FF6600"),
      tags: ["rabbitmq", "amqp", "cluster", "systemd", "quorum-queues"],
      author: "opensible",
      stars: 34,
      available: true,
      path: "IaC/blueprints/messaging/rabbitmq-cluster",
      templateId: "rabbitmq-cluster",
      filenameStem: "rabbitmq-cluster",
      defaults: {
        cluster_id: "opensible-rabbit",
        erlang_cookie: "",
        ssh_user_default: "root",
        ssh_port_default: 22,
        nodes: [
          { name: "rabbit-1", ip: "", ssh_user: "", ssh_port: "" },
          { name: "rabbit-2", ip: "", ssh_user: "", ssh_port: "" },
          { name: "rabbit-3", ip: "", ssh_user: "", ssh_port: "" },
        ],
        amqp_port: 5672,
        mgmt_port: 15672,
        prometheus_port: 15692,
        dist_port: 25672,
        epmd_port: 4369,
        admin_user: "admin",
        admin_password: "",
        delete_guest_user: true,
        default_queue_type: "quorum",
        vm_memory_high_watermark: "0.6",
        disk_free_limit: "2GB",
        open_firewall: true,
        become: true,
      },
    },
  ],
};
