import type { BlueprintGroup } from "./types";

const LOGO = (slug: string, color?: string) =>
  `https://cdn.simpleicons.org/${slug}${color ? `/${color}` : ""}`;

/**
 * Uninstall / cleanup blueprints. Each maps to the `uninstall-stack` backend
 * template with a preselected `stack` value. Runs official uninstallers plus
 * a hardened purge (data dirs, kubeconfigs, systemd units, iptables/ipvs).
 */
export const uninstallGroup: BlueprintGroup = {
  id: "uninstall",
  name: "Uninstall & Cleanup",
  description:
    "Cleanly remove previously-installed stacks from your hosts. Safe to re-run.",
  logo: LOGO("cachet", "EF4444"),
  blueprints: [
    {
      id: "uninstall-kubeadm",
      name: "Uninstall — Kubernetes (kubeadm)",
      description:
        "Run kubeadm reset, remove /etc/kubernetes, CNI, kubeconfigs, flush iptables/ipvs and purge kubelet/kubeadm/kubectl packages.",
      logo: LOGO("kubernetes", "326CE5"),
      tags: ["cleanup", "kubeadm", "kubernetes"],
      author: "opensible",
      stars: 12,
      available: true,
      path: "IaC/blueprints/uninstall/kubeadm",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-kubeadm",
      defaults: {
        stack: "kubeadm",
        purge_data: true,
        remove_packages: true,
        flush_iptables: true,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-k3s",
      name: "Uninstall — k3s Cluster",
      description:
        "Run the official k3s-uninstall.sh / k3s-agent-uninstall.sh, remove /var/lib/rancher, /etc/rancher, Longhorn data and kubeconfigs.",
      logo: LOGO("k3s", "FFC61C"),
      tags: ["cleanup", "k3s"],
      author: "opensible",
      stars: 10,
      available: true,
      path: "IaC/blueprints/uninstall/k3s",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-k3s",
      defaults: {
        stack: "k3s",
        purge_data: true,
        remove_packages: false,
        flush_iptables: true,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-docker",
      name: "Uninstall — Docker Engine",
      description:
        "Stop docker + containerd, remove all containers, purge docker-ce packages and delete /var/lib/docker & /var/lib/containerd.",
      logo: LOGO("docker", "2496ED"),
      tags: ["cleanup", "docker"],
      author: "opensible",
      stars: 9,
      available: true,
      path: "IaC/blueprints/uninstall/docker",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-docker",
      defaults: {
        stack: "docker",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-kafka",
      name: "Uninstall — Kafka (KRaft)",
      description:
        "Stop kafka.service, remove /opt/kafka, wipe /var/lib/kafka data + logs, drop the kafka system user and unit file.",
      logo: LOGO("apachekafka", "231F20"),
      tags: ["cleanup", "kafka", "kraft"],
      author: "opensible",
      stars: 7,
      available: true,
      path: "IaC/blueprints/uninstall/kafka",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-kafka",
      defaults: {
        stack: "kafka",
        purge_data: true,
        remove_packages: false,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-redpanda",
      name: "Uninstall — Redpanda + Console",
      description:
        "Stop redpanda and redpanda-console, purge the Redpanda apt/dnf repo, remove packages, /etc/redpanda, /var/lib/redpanda data and the redpanda system user.",
      logo: LOGO("redpanda", "E9165A"),
      tags: ["cleanup", "redpanda", "kafka-api"],
      author: "opensible",
      stars: 5,
      available: true,
      path: "IaC/blueprints/uninstall/redpanda",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-redpanda",
      defaults: {
        stack: "redpanda",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-argocd",
      name: "Uninstall — Argo CD (Helm)",
      description:
        "Run helm uninstall for the Argo CD release, remove argoproj.io CRDs and optionally delete the argocd namespace.",
      logo: LOGO("argo", "EF7B4D"),
      tags: ["cleanup", "argocd", "helm", "gitops"],
      author: "opensible",
      stars: 8,
      available: true,
      path: "IaC/blueprints/uninstall/argocd",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-argocd",
      defaults: {
        stack: "argocd",
        purge_data: false,
        remove_packages: false,
        flush_iptables: false,
        argocd_namespace: "argocd",
        argocd_release: "argocd",
        kubeconfig: "/etc/rancher/k3s/k3s.yaml",
        delete_namespace: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-redis",
      name: "Uninstall — Redis + Sentinel",
      description:
        "Stop redis-server and redis-sentinel, purge packages, remove /etc/redis, /var/lib/redis, /var/log/redis and the redis system user.",
      logo: LOGO("redis", "DC382D"),
      tags: ["cleanup", "redis", "sentinel"],
      author: "opensible",
      stars: 5,
      available: true,
      path: "IaC/blueprints/uninstall/redis",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-redis",
      defaults: {
        stack: "redis",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-valkey",
      name: "Uninstall — Valkey + Sentinel",
      description:
        "Stop valkey-server and valkey-sentinel, purge packages, remove /etc/valkey, /var/lib/valkey, /var/log/valkey and the valkey system user.",
      logo: "https://raw.githubusercontent.com/valkey-io/valkey/unstable/BRANDING/valkey-logomark.svg",
      tags: ["cleanup", "valkey", "sentinel"],
      author: "opensible",
      stars: 4,
      available: true,
      path: "IaC/blueprints/uninstall/valkey",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-valkey",
      defaults: {
        stack: "valkey",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-openbao",
      name: "Uninstall — OpenBao (systemd)",
      description:
        "Stop openbao.service, purge the OpenBao apt/dnf repo and package, remove /etc/openbao, /opt/openbao, /var/lib/openbao and the openbao system user.",
      logo: LOGO("vault", "FFEC6E"),
      tags: ["cleanup", "openbao", "vault", "secrets"],
      author: "opensible",
      stars: 4,
      available: true,
      path: "IaC/blueprints/uninstall/openbao",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-openbao",
      defaults: {
        stack: "openbao",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-patroni",
      name: "Uninstall — PostgreSQL HA (Patroni + etcd)",
      description:
        "Stop patroni + etcd, kill leftover postgres processes, purge PGDG packages, remove /opt/patroni venv, /etc/patroni, /var/lib/patroni, /var/lib/etcd and /var/lib/postgresql.",
      logo: LOGO("postgresql", "4169E1"),
      tags: ["cleanup", "postgres", "patroni", "etcd", "ha"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/patroni",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-patroni",
      defaults: {
        stack: "patroni",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-rabbitmq",
      name: "Uninstall — RabbitMQ Cluster",
      description:
        "Stop rabbitmq-server + epmd, kill leftover beam processes, purge packages, remove /etc/rabbitmq, /var/lib/rabbitmq, /var/log/rabbitmq and the Erlang cookie.",
      logo: LOGO("rabbitmq", "FF6600"),
      tags: ["cleanup", "rabbitmq", "amqp"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/rabbitmq",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-rabbitmq",
      defaults: {
        stack: "rabbitmq",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-haproxy",
      name: "Uninstall — HAProxy Load Balancer",
      description:
        "Stop haproxy + keepalived, kill leftover processes, purge packages and remove /etc/haproxy, /var/lib/haproxy, /run/haproxy, /var/log/haproxy* and /etc/keepalived.",
      logo: LOGO("haproxy", "106DA9"),
      tags: ["cleanup", "haproxy", "keepalived", "load-balancer"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/haproxy",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-haproxy",
      defaults: {
        stack: "haproxy",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-traefik",
      name: "Uninstall — Traefik Reverse Proxy / LB",
      description:
        "Stop traefik + keepalived, remove the /usr/local/bin/traefik binary and systemd unit, and purge /etc/traefik, /var/lib/traefik, /var/log/traefik and /etc/keepalived.",
      logo: LOGO("traefikproxy", "24A1C1"),
      tags: ["cleanup", "traefik", "keepalived", "reverse-proxy"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/traefik",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-traefik",
      defaults: {
        stack: "traefik",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-grafana",
      name: "Uninstall — Grafana OSS",
      description:
        "Stop grafana-server, purge the Grafana apt/dnf repo + package, and remove /etc/grafana, /var/lib/grafana and /var/log/grafana.",
      logo: LOGO("grafana", "F46800"),
      tags: ["cleanup", "grafana", "observability"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/grafana",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-grafana",
      defaults: {
        stack: "grafana",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-prometheus",
      name: "Uninstall — Prometheus (systemd)",
      description:
        "Stop prometheus.service, remove /usr/local/bin/{prometheus,promtool}, /etc/prometheus, /srv/metrics and the prometheus system user.",
      logo: LOGO("prometheus", "E6522C"),
      tags: ["cleanup", "prometheus", "metrics"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/prometheus",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-prometheus",
      defaults: {
        stack: "prometheus",
        purge_data: true,
        remove_packages: false,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-victoriametrics",
      name: "Uninstall — VictoriaMetrics (systemd)",
      description:
        "Stop victoriametrics.service, remove /usr/local/bin/victoria-metrics-prod, /srv/metrics data and the victoriametrics system user.",
      logo: LOGO("victoriametrics", "621773"),
      tags: ["cleanup", "victoriametrics", "metrics"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/victoriametrics",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-victoriametrics",
      defaults: {
        stack: "victoriametrics",
        purge_data: true,
        remove_packages: false,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-node-exporter",
      name: "Uninstall — Prometheus node_exporter",
      description:
        "Stop prometheus-node-exporter, remove the systemd drop-in and purge the distro package.",
      logo: LOGO("prometheus", "E6522C"),
      tags: ["cleanup", "node-exporter", "metrics"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/node-exporter",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-node-exporter",
      defaults: {
        stack: "node-exporter",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-elasticsearch",
      name: "Uninstall — Elasticsearch (Docker cluster)",
      description:
        "Stop elasticsearch-docker.service on every node, remove the Elasticsearch container and image, delete /var/lib/elasticsearch-data and the per-node health dashboard unit.",
      logo: LOGO("elasticsearch", "005571"),
      tags: ["cleanup", "elasticsearch", "elastic", "docker"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/elasticsearch",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-elasticsearch",
      defaults: {
        stack: "elasticsearch",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-logstash",
      name: "Uninstall — Logstash (Docker cluster)",
      description:
        "Stop logstash-docker.service on every node, remove the Logstash container and image, delete /etc/logstash, /var/lib/logstash and the per-node health dashboard unit.",
      logo: LOGO("logstash", "005571"),
      tags: ["cleanup", "logstash", "elastic", "docker"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/logstash",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-logstash",
      defaults: {
        stack: "logstash",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-kibana",
      name: "Uninstall — Kibana (Docker cluster)",
      description:
        "Stop kibana-docker.service on every node, remove the Kibana container and image, delete /var/lib/kibana and the per-node health dashboard unit.",
      logo: LOGO("kibana", "005571"),
      tags: ["cleanup", "kibana", "elastic", "docker"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/kibana",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-kibana",
      defaults: {
        stack: "kibana",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
    {
      id: "uninstall-vault-cluster",
      name: "Uninstall — HashiCorp Vault (Docker cluster)",
      description:
        "Stop vault-docker.service and the vault-autounseal service/timer on every node, remove the Vault container and image, and purge /etc/vault, /opt/vault and the Raft data directory (/var/lib/vault-data).",
      logo: LOGO("vault", "FFEC6E"),
      tags: ["cleanup", "vault", "hashicorp", "docker"],
      author: "opensible",
      stars: 3,
      available: true,
      path: "IaC/blueprints/uninstall/vault-cluster",
      templateId: "uninstall-stack",
      filenameStem: "uninstall-vault-cluster",
      defaults: {
        stack: "vault-cluster",
        purge_data: true,
        remove_packages: true,
        flush_iptables: false,
        reboot_after: false,
        become: true,
      },
    },
  ],
};

