"""Cost Analysis API blueprint."""
from __future__ import annotations

import logging
from flask import Blueprint, request, jsonify

from storage import cost_store

logger = logging.getLogger(__name__)
bp = Blueprint("cost_api", __name__, url_prefix="/api/cost")


def _project_id() -> str:
    return request.headers.get("X-Project-Id") or "default"


@bp.route("/pricing", methods=["GET"])
def list_pricing():
    return jsonify({"pricing": cost_store.list_pricing(), "providers": cost_store.SUPPORTED_PROVIDERS})


@bp.route("/pricing/<provider>", methods=["GET"])
def get_pricing(provider: str):
    try:
        return jsonify(cost_store.get_pricing(provider))
    except ValueError as e:
        return jsonify({"error": str(e)}), 400


@bp.route("/pricing/<provider>", methods=["PUT"])
def update_pricing(provider: str):
    body = request.get_json(silent=True) or {}
    try:
        saved = cost_store.save_pricing(provider, body, record_history=True)
        return jsonify(saved)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        logger.exception("save pricing failed")
        return jsonify({"error": str(e)}), 500


@bp.route("/pricing/<provider>/history", methods=["GET"])
def pricing_history(provider: str):
    return jsonify({"history": cost_store.get_pricing_history(provider)})


@bp.route("/estimate", methods=["POST"])
def estimate():
    body = request.get_json(silent=True) or {}
    provider = (body.get("provider") or "bytedc").lower()
    resources = body.get("resources") or []
    if not isinstance(resources, list):
        return jsonify({"error": "resources must be an array"}), 400
    try:
        result = cost_store.estimate_cost(provider, resources)
        return jsonify(result)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        logger.exception("estimate failed")
        return jsonify({"error": str(e)}), 500


@bp.route("/estimates", methods=["GET"])
def list_estimates():
    return jsonify({"estimates": cost_store.list_estimates(_project_id())})


@bp.route("/estimates", methods=["POST"])
def save_estimate():
    body = request.get_json(silent=True) or {}
    rec = cost_store.save_estimate(_project_id(), body)
    return jsonify(rec)


@bp.route("/estimates/<estimate_id>", methods=["DELETE"])
def delete_estimate(estimate_id: str):
    ok = cost_store.delete_estimate(_project_id(), estimate_id)
    if not ok:
        return jsonify({"error": "not found"}), 404
    return jsonify({"ok": True})


# ---- Reports (timestamped, per-project, generated by Apply or saved manually) -----

@bp.route("/reports", methods=["GET"])
def list_reports():
    stack = request.args.get("stack") or None
    return jsonify({"reports": cost_store.list_reports(_project_id(), stack=stack)})

@bp.route("/reports/<report_id>", methods=["GET"])
def get_report(report_id: str):
    rec = cost_store.get_report(_project_id(), report_id)
    if not rec:
        return jsonify({"error": "not found"}), 404
    return jsonify(rec)

@bp.route("/reports/<report_id>", methods=["DELETE"])
def delete_report(report_id: str):
    ok = cost_store.delete_report(_project_id(), report_id)
    if not ok:
        return jsonify({"error": "not found"}), 404
    return jsonify({"ok": True})

@bp.route("/reports", methods=["POST"])
def create_report():
    """Save a report explicitly (e.g. from the calculator)."""
    body = request.get_json(silent=True) or {}
    provider = (body.get("provider") or "bytedc").lower()
    resources = body.get("resources") or []
    stack = body.get("stack") or "manual"
    try:
        result = body.get("result") or cost_store.estimate_cost(provider, resources)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    rec = cost_store.save_report(
        _project_id(), provider, stack, resources, result,
        source=body.get("source") or "manual",
        run_id=body.get("run_id"),
        env=body.get("env"),
        cloud_project=body.get("cloud_project"),
    )
    return jsonify(rec)


# ---- Resource extraction from sources (best-effort, no external deps) -------------

@bp.route("/extract/plan", methods=["POST"])
def extract_from_plan():
    """Parse an OpenTofu/Terraform plan JSON and return a normalized resource list."""
    body = request.get_json(silent=True) or {}
    plan = body.get("plan")
    if isinstance(plan, str):
        import json
        try: plan = json.loads(plan)
        except Exception: return jsonify({"error": "plan must be valid JSON"}), 400
    if not isinstance(plan, dict):
        return jsonify({"error": "plan is required"}), 400

    resources = []
    changes = plan.get("resource_changes") or []
    if not changes and isinstance(plan.get("planned_values"), dict):
        root = plan["planned_values"].get("root_module") or {}
        changes = [{"type": r.get("type"), "name": r.get("name"), "change": {"after": r.get("values", {})}}
                   for r in (root.get("resources") or [])]

    def add(kind, name, **extra):
        resources.append({"kind": kind, "name": name, "quantity": 1, **extra})

    for ch in changes:
        ttype = (ch.get("type") or "").lower()
        name = ch.get("name") or ttype
        after = (ch.get("change") or {}).get("after") or {}
        if "instance" in ttype or ttype.endswith("_vm") or ttype.endswith("_server"):
            vcpu = after.get("vcpus") or after.get("cpu") or after.get("cores") or 2
            ram = after.get("memory_gb") or (after.get("memory", 4096) / 1024 if isinstance(after.get("memory"), (int, float)) else 4)
            add("instance", name, vcpu=vcpu, ram_gb=ram)
        elif "kubernetes" in ttype or ttype.endswith("_cluster"):
            add("kubernetes_cluster", name)
        elif "load_balancer" in ttype or ttype.endswith("_lb"):
            add("load_balancer", name)
        elif "nat" in ttype:
            add("nat_gateway", name)
        elif "vpn" in ttype:
            add("vpn_gateway", name)
        elif "public_ip" in ttype or ttype.endswith("_eip"):
            add("public_ip", name)
        elif "object" in ttype or "_bucket" in ttype or "_s3_bucket" in ttype:
            add("object_storage", name, size_gb=after.get("size_gb") or 100)
        elif "volume" in ttype or "disk" in ttype:
            size = after.get("size") or after.get("size_gb") or 50
            kind = "ssd" if (after.get("type") or "").lower() in ("ssd", "gp2", "gp3", "io1") else "ssd"
            add(kind, name, size_gb=size)
        elif "snapshot" in ttype:
            add("snapshot", name, size_gb=after.get("size_gb") or 20)
        elif "database" in ttype or ttype.endswith("_rds_instance") or ttype.endswith("_db_instance"):
            add("database", name)
        elif "dns_zone" in ttype or ttype.endswith("_zone"):
            add("dns_zone", name)
        elif "cdn" in ttype or "cloudfront" in ttype:
            add("cdn", name, bandwidth_gb=after.get("bandwidth_gb") or 100)
        elif "waf" in ttype:
            add("waf", name)
    return jsonify({"resources": resources, "count": len(resources)})
