# Generates an Ansible inventory file from Terraform outputs so
# step-02-configure-vms/ansible can run immediately after `tofu apply`.
#
# Written to: ../../step-02-configure-vms/ansible/inventory/${env}.ini

variable "env"          { type = string }
variable "output_dir"   {
  type    = string
  default = "../../../step-02-configure-vms/ansible/inventory"
}
variable "ssh_user" {
  type    = string
  default = "ubuntu"
}
variable "ssh_port" {
  type    = number
  default = 2222
}

variable "app_ips"      { type = list(string) }
variable "platform_ips" { type = map(list(string)) } # role => [ips]
variable "platform_eip_by_role" {
  type    = map(string)
  default = {}
}
variable "elb_eip" {
  type    = string
  default = ""
}
variable "nat_eip" {
  type    = string
  default = ""
}

locals {
  # For VMs without a public EIP, ansible must connect through the runner
  # (jump host). Runner gets its own EIP by default.
  jump_host = lookup(var.platform_eip_by_role, "runner", "")

  app_block = join("\n", [
    for idx, ip in var.app_ips :
    format("dbcs-%s-app-%02d ansible_host=%s", var.env, idx + 1, ip)
  ])

  platform_blocks = join("\n\n", [
    for role, ips in var.platform_ips :
    format(
      "[%s]\n%s",
      role,
      join("\n", [
        for idx, ip in ips :
        format(
          "dbcs-%s-%s-%02d ansible_host=%s",
          var.env, role, idx + 1,
          # If role has a public EIP, use it on the first member so ansible
          # can hit it directly without ProxyJump; others stay on private IPs.
          (idx == 0 && contains(keys(var.platform_eip_by_role), role))
            ? var.platform_eip_by_role[role]
            : ip
        )
      ])
    )
  ])
}

resource "local_file" "inventory" {
  filename = "${path.module}/${var.output_dir}/${var.env}.ini"
  content  = <<-EOT
    # AUTO-GENERATED by terraform module.inventory — do not edit by hand.
    # env: ${var.env}
    # elb_eip: ${var.elb_eip}
    # nat_eip: ${var.nat_eip}
    # jump_host (runner EIP): ${local.jump_host}

    [all:vars]
    ansible_user=${var.ssh_user}
    ansible_port=${var.ssh_port}
    ansible_ssh_common_args='-o StrictHostKeyChecking=no${local.jump_host == "" ? "" : " -o ProxyJump=${var.ssh_user}@${local.jump_host}:${var.ssh_port}"}'

    [app]
    ${local.app_block}

    ${local.platform_blocks}

    [dbcs:children]
    app
    ${join("\n", [for role in keys(var.platform_ips) : role])}
  EOT
}

output "inventory_path" { value = local_file.inventory.filename }
