/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemWorkersRouteImport } from './routes/system/workers'
import { Route as SystemUsersRouteImport } from './routes/system/users'
import { Route as SystemSettingsRouteImport } from './routes/system/settings'
import { Route as SystemServerLogsRouteImport } from './routes/system/server-logs'
import { Route as SystemSecretsRouteImport } from './routes/system/secrets'
import { Route as SystemApiRouteImport } from './routes/system/api'
import { Route as InfrastructureVaultsSecretsRouteImport } from './routes/infrastructure/vaults-secrets'
import { Route as InfrastructureVaultsRouteImport } from './routes/infrastructure/vaults'
import { Route as InfrastructureTemplatesRouteImport } from './routes/infrastructure/templates'
import { Route as InfrastructureSecretsRouteImport } from './routes/infrastructure/secrets'
import { Route as InfrastructureRolesRouteImport } from './routes/infrastructure/roles'
import { Route as InfrastructurePlaybooksRolesRouteImport } from './routes/infrastructure/playbooks-roles'
import { Route as InfrastructurePlaybooksRouteImport } from './routes/infrastructure/playbooks'
import { Route as InfrastructureJobRouteImport } from './routes/infrastructure/job'
import { Route as InfrastructureHostsRouteImport } from './routes/infrastructure/hosts'
import { Route as InfrastructureDeploymentRouteImport } from './routes/infrastructure/deployment'
import { Route as CloudSummaryRouteImport } from './routes/cloud/summary'
import { Route as CloudSettingsRouteImport } from './routes/cloud/settings'
import { Route as CloudCostRouteImport } from './routes/cloud/cost'
import { Route as CloudStacksIndexRouteImport } from './routes/cloud/stacks/index'
import { Route as CloudStacksNewRouteImport } from './routes/cloud/stacks/new'
import { Route as CloudStacksStackIdRouteImport } from './routes/cloud/stacks/$stackId'
import { Route as CloudStacksNewKubernetesRouteImport } from './routes/cloud/stacks/new.kubernetes'
import { Route as CloudStacksNewImportRouteImport } from './routes/cloud/stacks/new.import'
import { Route as CloudStacksNewHetznerRouteImport } from './routes/cloud/stacks/new.hetzner'
import { Route as CloudStacksNewGkeRouteImport } from './routes/cloud/stacks/new.gke'
import { Route as CloudStacksNewGcpRouteImport } from './routes/cloud/stacks/new.gcp'
import { Route as CloudStacksNewEksRouteImport } from './routes/cloud/stacks/new.eks'
import { Route as CloudStacksNewCloudflareRouteImport } from './routes/cloud/stacks/new.cloudflare'
import { Route as CloudStacksNewBytedcRouteImport } from './routes/cloud/stacks/new.bytedc'
import { Route as CloudStacksNewAwsRouteImport } from './routes/cloud/stacks/new.aws'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemWorkersRoute = SystemWorkersRouteImport.update({
  id: '/system/workers',
  path: '/system/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUsersRoute = SystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemServerLogsRoute = SystemServerLogsRouteImport.update({
  id: '/system/server-logs',
  path: '/system/server-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSecretsRoute = SystemSecretsRouteImport.update({
  id: '/system/secrets',
  path: '/system/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemApiRoute = SystemApiRouteImport.update({
  id: '/system/api',
  path: '/system/api',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureVaultsSecretsRoute =
  InfrastructureVaultsSecretsRouteImport.update({
    id: '/infrastructure/vaults-secrets',
    path: '/infrastructure/vaults-secrets',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfrastructureVaultsRoute = InfrastructureVaultsRouteImport.update({
  id: '/infrastructure/vaults',
  path: '/infrastructure/vaults',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureTemplatesRoute = InfrastructureTemplatesRouteImport.update({
  id: '/infrastructure/templates',
  path: '/infrastructure/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureSecretsRoute = InfrastructureSecretsRouteImport.update({
  id: '/infrastructure/secrets',
  path: '/infrastructure/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRolesRoute = InfrastructureRolesRouteImport.update({
  id: '/infrastructure/roles',
  path: '/infrastructure/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructurePlaybooksRolesRoute =
  InfrastructurePlaybooksRolesRouteImport.update({
    id: '/infrastructure/playbooks-roles',
    path: '/infrastructure/playbooks-roles',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfrastructurePlaybooksRoute = InfrastructurePlaybooksRouteImport.update({
  id: '/infrastructure/playbooks',
  path: '/infrastructure/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureJobRoute = InfrastructureJobRouteImport.update({
  id: '/infrastructure/job',
  path: '/infrastructure/job',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureHostsRoute = InfrastructureHostsRouteImport.update({
  id: '/infrastructure/hosts',
  path: '/infrastructure/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureDeploymentRoute =
  InfrastructureDeploymentRouteImport.update({
    id: '/infrastructure/deployment',
    path: '/infrastructure/deployment',
    getParentRoute: () => rootRouteImport,
  } as any)
const CloudSummaryRoute = CloudSummaryRouteImport.update({
  id: '/cloud/summary',
  path: '/cloud/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudSettingsRoute = CloudSettingsRouteImport.update({
  id: '/cloud/settings',
  path: '/cloud/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudCostRoute = CloudCostRouteImport.update({
  id: '/cloud/cost',
  path: '/cloud/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudStacksIndexRoute = CloudStacksIndexRouteImport.update({
  id: '/cloud/stacks/',
  path: '/cloud/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudStacksNewRoute = CloudStacksNewRouteImport.update({
  id: '/cloud/stacks/new',
  path: '/cloud/stacks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudStacksStackIdRoute = CloudStacksStackIdRouteImport.update({
  id: '/cloud/stacks/$stackId',
  path: '/cloud/stacks/$stackId',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudStacksNewKubernetesRoute =
  CloudStacksNewKubernetesRouteImport.update({
    id: '/kubernetes',
    path: '/kubernetes',
    getParentRoute: () => CloudStacksNewRoute,
  } as any)
const CloudStacksNewImportRoute = CloudStacksNewImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => CloudStacksNewRoute,
} as any)
const CloudStacksNewHetznerRoute = CloudStacksNewHetznerRouteImport.update({
  id: '/hetzner',
  path: '/hetzner',
  getParentRoute: () => CloudStacksNewRoute,
} as any)
const CloudStacksNewGkeRoute = CloudStacksNewGkeRouteImport.update({
  id: '/gke',
  path: '/gke',
  getParentRoute: () => CloudStacksNewRoute,
} as any)
const CloudStacksNewGcpRoute = CloudStacksNewGcpRouteImport.update({
  id: '/gcp',
  path: '/gcp',
  getParentRoute: () => CloudStacksNewRoute,
} as any)
const CloudStacksNewEksRoute = CloudStacksNewEksRouteImport.update({
  id: '/eks',
  path: '/eks',
  getParentRoute: () => CloudStacksNewRoute,
} as any)
const CloudStacksNewCloudflareRoute =
  CloudStacksNewCloudflareRouteImport.update({
    id: '/cloudflare',
    path: '/cloudflare',
    getParentRoute: () => CloudStacksNewRoute,
  } as any)
const CloudStacksNewBytedcRoute = CloudStacksNewBytedcRouteImport.update({
  id: '/bytedc',
  path: '/bytedc',
  getParentRoute: () => CloudStacksNewRoute,
} as any)
const CloudStacksNewAwsRoute = CloudStacksNewAwsRouteImport.update({
  id: '/aws',
  path: '/aws',
  getParentRoute: () => CloudStacksNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/cloud/cost': typeof CloudCostRoute
  '/cloud/settings': typeof CloudSettingsRoute
  '/cloud/summary': typeof CloudSummaryRoute
  '/infrastructure/deployment': typeof InfrastructureDeploymentRoute
  '/infrastructure/hosts': typeof InfrastructureHostsRoute
  '/infrastructure/job': typeof InfrastructureJobRoute
  '/infrastructure/playbooks': typeof InfrastructurePlaybooksRoute
  '/infrastructure/playbooks-roles': typeof InfrastructurePlaybooksRolesRoute
  '/infrastructure/roles': typeof InfrastructureRolesRoute
  '/infrastructure/secrets': typeof InfrastructureSecretsRoute
  '/infrastructure/templates': typeof InfrastructureTemplatesRoute
  '/infrastructure/vaults': typeof InfrastructureVaultsRoute
  '/infrastructure/vaults-secrets': typeof InfrastructureVaultsSecretsRoute
  '/system/api': typeof SystemApiRoute
  '/system/secrets': typeof SystemSecretsRoute
  '/system/server-logs': typeof SystemServerLogsRoute
  '/system/settings': typeof SystemSettingsRoute
  '/system/users': typeof SystemUsersRoute
  '/system/workers': typeof SystemWorkersRoute
  '/cloud/stacks/$stackId': typeof CloudStacksStackIdRoute
  '/cloud/stacks/new': typeof CloudStacksNewRouteWithChildren
  '/cloud/stacks/': typeof CloudStacksIndexRoute
  '/cloud/stacks/new/aws': typeof CloudStacksNewAwsRoute
  '/cloud/stacks/new/bytedc': typeof CloudStacksNewBytedcRoute
  '/cloud/stacks/new/cloudflare': typeof CloudStacksNewCloudflareRoute
  '/cloud/stacks/new/eks': typeof CloudStacksNewEksRoute
  '/cloud/stacks/new/gcp': typeof CloudStacksNewGcpRoute
  '/cloud/stacks/new/gke': typeof CloudStacksNewGkeRoute
  '/cloud/stacks/new/hetzner': typeof CloudStacksNewHetznerRoute
  '/cloud/stacks/new/import': typeof CloudStacksNewImportRoute
  '/cloud/stacks/new/kubernetes': typeof CloudStacksNewKubernetesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/cloud/cost': typeof CloudCostRoute
  '/cloud/settings': typeof CloudSettingsRoute
  '/cloud/summary': typeof CloudSummaryRoute
  '/infrastructure/deployment': typeof InfrastructureDeploymentRoute
  '/infrastructure/hosts': typeof InfrastructureHostsRoute
  '/infrastructure/job': typeof InfrastructureJobRoute
  '/infrastructure/playbooks': typeof InfrastructurePlaybooksRoute
  '/infrastructure/playbooks-roles': typeof InfrastructurePlaybooksRolesRoute
  '/infrastructure/roles': typeof InfrastructureRolesRoute
  '/infrastructure/secrets': typeof InfrastructureSecretsRoute
  '/infrastructure/templates': typeof InfrastructureTemplatesRoute
  '/infrastructure/vaults': typeof InfrastructureVaultsRoute
  '/infrastructure/vaults-secrets': typeof InfrastructureVaultsSecretsRoute
  '/system/api': typeof SystemApiRoute
  '/system/secrets': typeof SystemSecretsRoute
  '/system/server-logs': typeof SystemServerLogsRoute
  '/system/settings': typeof SystemSettingsRoute
  '/system/users': typeof SystemUsersRoute
  '/system/workers': typeof SystemWorkersRoute
  '/cloud/stacks/$stackId': typeof CloudStacksStackIdRoute
  '/cloud/stacks/new': typeof CloudStacksNewRouteWithChildren
  '/cloud/stacks': typeof CloudStacksIndexRoute
  '/cloud/stacks/new/aws': typeof CloudStacksNewAwsRoute
  '/cloud/stacks/new/bytedc': typeof CloudStacksNewBytedcRoute
  '/cloud/stacks/new/cloudflare': typeof CloudStacksNewCloudflareRoute
  '/cloud/stacks/new/eks': typeof CloudStacksNewEksRoute
  '/cloud/stacks/new/gcp': typeof CloudStacksNewGcpRoute
  '/cloud/stacks/new/gke': typeof CloudStacksNewGkeRoute
  '/cloud/stacks/new/hetzner': typeof CloudStacksNewHetznerRoute
  '/cloud/stacks/new/import': typeof CloudStacksNewImportRoute
  '/cloud/stacks/new/kubernetes': typeof CloudStacksNewKubernetesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/cloud/cost': typeof CloudCostRoute
  '/cloud/settings': typeof CloudSettingsRoute
  '/cloud/summary': typeof CloudSummaryRoute
  '/infrastructure/deployment': typeof InfrastructureDeploymentRoute
  '/infrastructure/hosts': typeof InfrastructureHostsRoute
  '/infrastructure/job': typeof InfrastructureJobRoute
  '/infrastructure/playbooks': typeof InfrastructurePlaybooksRoute
  '/infrastructure/playbooks-roles': typeof InfrastructurePlaybooksRolesRoute
  '/infrastructure/roles': typeof InfrastructureRolesRoute
  '/infrastructure/secrets': typeof InfrastructureSecretsRoute
  '/infrastructure/templates': typeof InfrastructureTemplatesRoute
  '/infrastructure/vaults': typeof InfrastructureVaultsRoute
  '/infrastructure/vaults-secrets': typeof InfrastructureVaultsSecretsRoute
  '/system/api': typeof SystemApiRoute
  '/system/secrets': typeof SystemSecretsRoute
  '/system/server-logs': typeof SystemServerLogsRoute
  '/system/settings': typeof SystemSettingsRoute
  '/system/users': typeof SystemUsersRoute
  '/system/workers': typeof SystemWorkersRoute
  '/cloud/stacks/$stackId': typeof CloudStacksStackIdRoute
  '/cloud/stacks/new': typeof CloudStacksNewRouteWithChildren
  '/cloud/stacks/': typeof CloudStacksIndexRoute
  '/cloud/stacks/new/aws': typeof CloudStacksNewAwsRoute
  '/cloud/stacks/new/bytedc': typeof CloudStacksNewBytedcRoute
  '/cloud/stacks/new/cloudflare': typeof CloudStacksNewCloudflareRoute
  '/cloud/stacks/new/eks': typeof CloudStacksNewEksRoute
  '/cloud/stacks/new/gcp': typeof CloudStacksNewGcpRoute
  '/cloud/stacks/new/gke': typeof CloudStacksNewGkeRoute
  '/cloud/stacks/new/hetzner': typeof CloudStacksNewHetznerRoute
  '/cloud/stacks/new/import': typeof CloudStacksNewImportRoute
  '/cloud/stacks/new/kubernetes': typeof CloudStacksNewKubernetesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/settings'
    | '/cloud/cost'
    | '/cloud/settings'
    | '/cloud/summary'
    | '/infrastructure/deployment'
    | '/infrastructure/hosts'
    | '/infrastructure/job'
    | '/infrastructure/playbooks'
    | '/infrastructure/playbooks-roles'
    | '/infrastructure/roles'
    | '/infrastructure/secrets'
    | '/infrastructure/templates'
    | '/infrastructure/vaults'
    | '/infrastructure/vaults-secrets'
    | '/system/api'
    | '/system/secrets'
    | '/system/server-logs'
    | '/system/settings'
    | '/system/users'
    | '/system/workers'
    | '/cloud/stacks/$stackId'
    | '/cloud/stacks/new'
    | '/cloud/stacks/'
    | '/cloud/stacks/new/aws'
    | '/cloud/stacks/new/bytedc'
    | '/cloud/stacks/new/cloudflare'
    | '/cloud/stacks/new/eks'
    | '/cloud/stacks/new/gcp'
    | '/cloud/stacks/new/gke'
    | '/cloud/stacks/new/hetzner'
    | '/cloud/stacks/new/import'
    | '/cloud/stacks/new/kubernetes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/settings'
    | '/cloud/cost'
    | '/cloud/settings'
    | '/cloud/summary'
    | '/infrastructure/deployment'
    | '/infrastructure/hosts'
    | '/infrastructure/job'
    | '/infrastructure/playbooks'
    | '/infrastructure/playbooks-roles'
    | '/infrastructure/roles'
    | '/infrastructure/secrets'
    | '/infrastructure/templates'
    | '/infrastructure/vaults'
    | '/infrastructure/vaults-secrets'
    | '/system/api'
    | '/system/secrets'
    | '/system/server-logs'
    | '/system/settings'
    | '/system/users'
    | '/system/workers'
    | '/cloud/stacks/$stackId'
    | '/cloud/stacks/new'
    | '/cloud/stacks'
    | '/cloud/stacks/new/aws'
    | '/cloud/stacks/new/bytedc'
    | '/cloud/stacks/new/cloudflare'
    | '/cloud/stacks/new/eks'
    | '/cloud/stacks/new/gcp'
    | '/cloud/stacks/new/gke'
    | '/cloud/stacks/new/hetzner'
    | '/cloud/stacks/new/import'
    | '/cloud/stacks/new/kubernetes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/settings'
    | '/cloud/cost'
    | '/cloud/settings'
    | '/cloud/summary'
    | '/infrastructure/deployment'
    | '/infrastructure/hosts'
    | '/infrastructure/job'
    | '/infrastructure/playbooks'
    | '/infrastructure/playbooks-roles'
    | '/infrastructure/roles'
    | '/infrastructure/secrets'
    | '/infrastructure/templates'
    | '/infrastructure/vaults'
    | '/infrastructure/vaults-secrets'
    | '/system/api'
    | '/system/secrets'
    | '/system/server-logs'
    | '/system/settings'
    | '/system/users'
    | '/system/workers'
    | '/cloud/stacks/$stackId'
    | '/cloud/stacks/new'
    | '/cloud/stacks/'
    | '/cloud/stacks/new/aws'
    | '/cloud/stacks/new/bytedc'
    | '/cloud/stacks/new/cloudflare'
    | '/cloud/stacks/new/eks'
    | '/cloud/stacks/new/gcp'
    | '/cloud/stacks/new/gke'
    | '/cloud/stacks/new/hetzner'
    | '/cloud/stacks/new/import'
    | '/cloud/stacks/new/kubernetes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  CloudCostRoute: typeof CloudCostRoute
  CloudSettingsRoute: typeof CloudSettingsRoute
  CloudSummaryRoute: typeof CloudSummaryRoute
  InfrastructureDeploymentRoute: typeof InfrastructureDeploymentRoute
  InfrastructureHostsRoute: typeof InfrastructureHostsRoute
  InfrastructureJobRoute: typeof InfrastructureJobRoute
  InfrastructurePlaybooksRoute: typeof InfrastructurePlaybooksRoute
  InfrastructurePlaybooksRolesRoute: typeof InfrastructurePlaybooksRolesRoute
  InfrastructureRolesRoute: typeof InfrastructureRolesRoute
  InfrastructureSecretsRoute: typeof InfrastructureSecretsRoute
  InfrastructureTemplatesRoute: typeof InfrastructureTemplatesRoute
  InfrastructureVaultsRoute: typeof InfrastructureVaultsRoute
  InfrastructureVaultsSecretsRoute: typeof InfrastructureVaultsSecretsRoute
  SystemApiRoute: typeof SystemApiRoute
  SystemSecretsRoute: typeof SystemSecretsRoute
  SystemServerLogsRoute: typeof SystemServerLogsRoute
  SystemSettingsRoute: typeof SystemSettingsRoute
  SystemUsersRoute: typeof SystemUsersRoute
  SystemWorkersRoute: typeof SystemWorkersRoute
  CloudStacksStackIdRoute: typeof CloudStacksStackIdRoute
  CloudStacksNewRoute: typeof CloudStacksNewRouteWithChildren
  CloudStacksIndexRoute: typeof CloudStacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/workers': {
      id: '/system/workers'
      path: '/system/workers'
      fullPath: '/system/workers'
      preLoaderRoute: typeof SystemWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/users': {
      id: '/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof SystemUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/settings': {
      id: '/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/server-logs': {
      id: '/system/server-logs'
      path: '/system/server-logs'
      fullPath: '/system/server-logs'
      preLoaderRoute: typeof SystemServerLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/secrets': {
      id: '/system/secrets'
      path: '/system/secrets'
      fullPath: '/system/secrets'
      preLoaderRoute: typeof SystemSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/api': {
      id: '/system/api'
      path: '/system/api'
      fullPath: '/system/api'
      preLoaderRoute: typeof SystemApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/vaults-secrets': {
      id: '/infrastructure/vaults-secrets'
      path: '/infrastructure/vaults-secrets'
      fullPath: '/infrastructure/vaults-secrets'
      preLoaderRoute: typeof InfrastructureVaultsSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/vaults': {
      id: '/infrastructure/vaults'
      path: '/infrastructure/vaults'
      fullPath: '/infrastructure/vaults'
      preLoaderRoute: typeof InfrastructureVaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/templates': {
      id: '/infrastructure/templates'
      path: '/infrastructure/templates'
      fullPath: '/infrastructure/templates'
      preLoaderRoute: typeof InfrastructureTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/secrets': {
      id: '/infrastructure/secrets'
      path: '/infrastructure/secrets'
      fullPath: '/infrastructure/secrets'
      preLoaderRoute: typeof InfrastructureSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/roles': {
      id: '/infrastructure/roles'
      path: '/infrastructure/roles'
      fullPath: '/infrastructure/roles'
      preLoaderRoute: typeof InfrastructureRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/playbooks-roles': {
      id: '/infrastructure/playbooks-roles'
      path: '/infrastructure/playbooks-roles'
      fullPath: '/infrastructure/playbooks-roles'
      preLoaderRoute: typeof InfrastructurePlaybooksRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/playbooks': {
      id: '/infrastructure/playbooks'
      path: '/infrastructure/playbooks'
      fullPath: '/infrastructure/playbooks'
      preLoaderRoute: typeof InfrastructurePlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/job': {
      id: '/infrastructure/job'
      path: '/infrastructure/job'
      fullPath: '/infrastructure/job'
      preLoaderRoute: typeof InfrastructureJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/hosts': {
      id: '/infrastructure/hosts'
      path: '/infrastructure/hosts'
      fullPath: '/infrastructure/hosts'
      preLoaderRoute: typeof InfrastructureHostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/deployment': {
      id: '/infrastructure/deployment'
      path: '/infrastructure/deployment'
      fullPath: '/infrastructure/deployment'
      preLoaderRoute: typeof InfrastructureDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud/summary': {
      id: '/cloud/summary'
      path: '/cloud/summary'
      fullPath: '/cloud/summary'
      preLoaderRoute: typeof CloudSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud/settings': {
      id: '/cloud/settings'
      path: '/cloud/settings'
      fullPath: '/cloud/settings'
      preLoaderRoute: typeof CloudSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud/cost': {
      id: '/cloud/cost'
      path: '/cloud/cost'
      fullPath: '/cloud/cost'
      preLoaderRoute: typeof CloudCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud/stacks/': {
      id: '/cloud/stacks/'
      path: '/cloud/stacks'
      fullPath: '/cloud/stacks/'
      preLoaderRoute: typeof CloudStacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud/stacks/new': {
      id: '/cloud/stacks/new'
      path: '/cloud/stacks/new'
      fullPath: '/cloud/stacks/new'
      preLoaderRoute: typeof CloudStacksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud/stacks/$stackId': {
      id: '/cloud/stacks/$stackId'
      path: '/cloud/stacks/$stackId'
      fullPath: '/cloud/stacks/$stackId'
      preLoaderRoute: typeof CloudStacksStackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud/stacks/new/kubernetes': {
      id: '/cloud/stacks/new/kubernetes'
      path: '/kubernetes'
      fullPath: '/cloud/stacks/new/kubernetes'
      preLoaderRoute: typeof CloudStacksNewKubernetesRouteImport
      parentRoute: typeof CloudStacksNewRoute
    }
    '/cloud/stacks/new/import': {
      id: '/cloud/stacks/new/import'
      path: '/import'
      fullPath: '/cloud/stacks/new/import'
      preLoaderRoute: typeof CloudStacksNewImportRouteImport
      parentRoute: typeof CloudStacksNewRoute
    }
    '/cloud/stacks/new/hetzner': {
      id: '/cloud/stacks/new/hetzner'
      path: '/hetzner'
      fullPath: '/cloud/stacks/new/hetzner'
      preLoaderRoute: typeof CloudStacksNewHetznerRouteImport
      parentRoute: typeof CloudStacksNewRoute
    }
    '/cloud/stacks/new/gke': {
      id: '/cloud/stacks/new/gke'
      path: '/gke'
      fullPath: '/cloud/stacks/new/gke'
      preLoaderRoute: typeof CloudStacksNewGkeRouteImport
      parentRoute: typeof CloudStacksNewRoute
    }
    '/cloud/stacks/new/gcp': {
      id: '/cloud/stacks/new/gcp'
      path: '/gcp'
      fullPath: '/cloud/stacks/new/gcp'
      preLoaderRoute: typeof CloudStacksNewGcpRouteImport
      parentRoute: typeof CloudStacksNewRoute
    }
    '/cloud/stacks/new/eks': {
      id: '/cloud/stacks/new/eks'
      path: '/eks'
      fullPath: '/cloud/stacks/new/eks'
      preLoaderRoute: typeof CloudStacksNewEksRouteImport
      parentRoute: typeof CloudStacksNewRoute
    }
    '/cloud/stacks/new/cloudflare': {
      id: '/cloud/stacks/new/cloudflare'
      path: '/cloudflare'
      fullPath: '/cloud/stacks/new/cloudflare'
      preLoaderRoute: typeof CloudStacksNewCloudflareRouteImport
      parentRoute: typeof CloudStacksNewRoute
    }
    '/cloud/stacks/new/bytedc': {
      id: '/cloud/stacks/new/bytedc'
      path: '/bytedc'
      fullPath: '/cloud/stacks/new/bytedc'
      preLoaderRoute: typeof CloudStacksNewBytedcRouteImport
      parentRoute: typeof CloudStacksNewRoute
    }
    '/cloud/stacks/new/aws': {
      id: '/cloud/stacks/new/aws'
      path: '/aws'
      fullPath: '/cloud/stacks/new/aws'
      preLoaderRoute: typeof CloudStacksNewAwsRouteImport
      parentRoute: typeof CloudStacksNewRoute
    }
  }
}

interface CloudStacksNewRouteChildren {
  CloudStacksNewAwsRoute: typeof CloudStacksNewAwsRoute
  CloudStacksNewBytedcRoute: typeof CloudStacksNewBytedcRoute
  CloudStacksNewCloudflareRoute: typeof CloudStacksNewCloudflareRoute
  CloudStacksNewEksRoute: typeof CloudStacksNewEksRoute
  CloudStacksNewGcpRoute: typeof CloudStacksNewGcpRoute
  CloudStacksNewGkeRoute: typeof CloudStacksNewGkeRoute
  CloudStacksNewHetznerRoute: typeof CloudStacksNewHetznerRoute
  CloudStacksNewImportRoute: typeof CloudStacksNewImportRoute
  CloudStacksNewKubernetesRoute: typeof CloudStacksNewKubernetesRoute
}

const CloudStacksNewRouteChildren: CloudStacksNewRouteChildren = {
  CloudStacksNewAwsRoute: CloudStacksNewAwsRoute,
  CloudStacksNewBytedcRoute: CloudStacksNewBytedcRoute,
  CloudStacksNewCloudflareRoute: CloudStacksNewCloudflareRoute,
  CloudStacksNewEksRoute: CloudStacksNewEksRoute,
  CloudStacksNewGcpRoute: CloudStacksNewGcpRoute,
  CloudStacksNewGkeRoute: CloudStacksNewGkeRoute,
  CloudStacksNewHetznerRoute: CloudStacksNewHetznerRoute,
  CloudStacksNewImportRoute: CloudStacksNewImportRoute,
  CloudStacksNewKubernetesRoute: CloudStacksNewKubernetesRoute,
}

const CloudStacksNewRouteWithChildren = CloudStacksNewRoute._addFileChildren(
  CloudStacksNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  CloudCostRoute: CloudCostRoute,
  CloudSettingsRoute: CloudSettingsRoute,
  CloudSummaryRoute: CloudSummaryRoute,
  InfrastructureDeploymentRoute: InfrastructureDeploymentRoute,
  InfrastructureHostsRoute: InfrastructureHostsRoute,
  InfrastructureJobRoute: InfrastructureJobRoute,
  InfrastructurePlaybooksRoute: InfrastructurePlaybooksRoute,
  InfrastructurePlaybooksRolesRoute: InfrastructurePlaybooksRolesRoute,
  InfrastructureRolesRoute: InfrastructureRolesRoute,
  InfrastructureSecretsRoute: InfrastructureSecretsRoute,
  InfrastructureTemplatesRoute: InfrastructureTemplatesRoute,
  InfrastructureVaultsRoute: InfrastructureVaultsRoute,
  InfrastructureVaultsSecretsRoute: InfrastructureVaultsSecretsRoute,
  SystemApiRoute: SystemApiRoute,
  SystemSecretsRoute: SystemSecretsRoute,
  SystemServerLogsRoute: SystemServerLogsRoute,
  SystemSettingsRoute: SystemSettingsRoute,
  SystemUsersRoute: SystemUsersRoute,
  SystemWorkersRoute: SystemWorkersRoute,
  CloudStacksStackIdRoute: CloudStacksStackIdRoute,
  CloudStacksNewRoute: CloudStacksNewRouteWithChildren,
  CloudStacksIndexRoute: CloudStacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
